config/routes.rb
OutdoorJournal::Application.routes.draw do

  resources :adventure_tags, only: [:destroy, :edit, :new, :create]
  get "adventure_tags/new"
  get "adventure_tags/create"
  get "adventure_tags/update"
  get "adventure_tags/edit"
  resources :adventure_types, only: [:edit, :new, :create, :destroy, :index, :show, :update]
  get "adventure_types/:id", to: 'adventure_types#show'
  get "adventure_types/new"
  get "adventure_types/edit"
  delete "adventure_types/destroy"
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  root  'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

  delete "adventure_coordinates/destroy_all_for_adventure"

  resources :adventure_tags, only: [:new, :edit, :create, :destroy]

  get "adventures/test"
  get "adventures/upload"
  post "adventures/parse"
  resources :adventures
  get "adventures/create"
  get "adventures/show"
  get "adventures/edit"
  delete "adventures/destroy"
  resources :users
  get "users/new"
  match '/signup', to: 'users#new', via: 'get'
  get 'users/:id', to: 'users#show', as: 'profile'
  get 'adventure_coordinates/edit'
  delete 'adventure_coordinates/delete_coords'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Outdoor Journal | <%= yield(:title) %></title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyCarFkFloIvQnB_gMYoFEZltyDk4K7vQfQ&sensor=false" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <div id="banner_wrapper">
      <div id="top_links_wrapper">
        <div id="top_links">
          <ul id="top_links_list">
           <% if signed_in? %>
            <li id="top_links_list"><%= link_to "Home", root_path %> </li>
            <li id="top_links_list"><%= link_to "Adventures", adventures_path %> </li>
            <li id="top_links_list"><%= link_to "Profile", @user %> </li> 
            <li id="top_links_list"> <%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
            <li id="top_links_list"><%= link_to "Home", root_path %> </li>
            <li id="top_links_list"> <%= link_to "Sign Up", signup_path %></li>
            <li id="top_links_list"> <%= link_to "Sign In", signin_path %></li>
          <% end %>

          </ul>
        </div>
      </div>
        <%= image_tag("banner.png", {:id=> "banner", :align=> "middle"}) %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </div>
  <div id="footer_wrapper">
    <div id="footer_text">
      <p>Outdoor Journal Copyright 2014</p>
    </div>
  </div>
</body>
</html>